services:
  db:
    image: postgres:15
    container_name: postgres_db_local
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: alae1ajbar/crawlic:latest
    container_name: django_app_local
    restart: unless-stopped
    command: gunicorn main:app --bind 0.0.0.0:9500 --workers 3 --timeout 120
    ports:
      - "9500:9500"  # Expose directly for local development
    volumes:
      - static_volume:/app/static
      # Optional: mount local code for development
      - ./:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_server_local
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: