services:
  db:
    image: postgres:15
    container_name: crawlic_postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - crawlic_postgres_volume:/var/lib/postgresql/data

  web:
    image: alae1ajbar/crawlic:latest
    container_name: flask_api
    restart: unless-stopped
    command: gunicorn app:app --bind 0.0.0.0:9500 --workers 3 --timeout 120
    expose:
      - "9500"
    volumes:
      - crawlic_static_volume:/app/static
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"      # Changed from 80:80
      - "8443:443"     # Changed from 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - crawlic_static_volume:/app/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: