version: '3.8'

services:
  db:
    image: postgres:15
    container_name: crawlic_postgres_local
    restart: unless-stopped
    networks:
      - crawlic-internal
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"  # Expose PostgreSQL for local DB tools

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawlic_flask_local
    restart: unless-stopped
    command: gunicorn main:app --bind 0.0.0.0:9500 --workers 3 --timeout 120
    networks:
      - crawlic-internal
    volumes:
      - static_volume:/app/static
      - /dev/shm:/dev/shm
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ORGANIZATION_ID: ${ORGANIZATION_ID}
      PROJECT_ID: ${PROJECT_ID}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
    shm_size: '2gb'
    ports:
      - "9500:9500"  # Expose Flask directly for debugging

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crawlic_frontend_local
    restart: unless-stopped
    networks:
      - crawlic-internal
    ports:
      - "3000:80"  # Expose frontend directly

  nginx:
    image: nginx:alpine
    container_name: crawlic_nginx_local
    restart: unless-stopped
    depends_on:
      - web
      - frontend
    networks:
      - crawlic-internal
    volumes:
      - static_volume:/app/static
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"  # Expose nginx on local port 8000

networks:
  crawlic-internal:
    driver: bridge

volumes:
  postgres_data:
  static_volume: